export type Category = "mobile" | "web" | "design";
export type Subcategory = 
  | "android" | "ios" | "react-native" | "flutter" | "jetpack-compose"
  | "react" | "vue" | "svelte" | "css" | "tailwind"
  | "figma" | "framer" | "webflow";

export interface Resource {
  id: string;
  slug: string;
  title: string;
  titleEn: string;
  description: string;
  descriptionEn: string;
  author: string;
  authorAvatar?: string;
  category: Category;
  subcategory: Subcategory;
  tags: string[];
  dateAdded: string;
  link: string;
  demoComponent: string;
  featured?: boolean;
}

export const resources: Resource[] = [
  // ==================== REACT (20个) ====================
  {
    id: "r1",
    slug: "react-magic-ui",
    title: "React Magic UI",
    titleEn: "React Magic UI",
    description: "一个包含 Liquid Glass 效果的 React 组件库，提供丰富的动画和交互效果。",
    descriptionEn: "A React component library featuring Liquid Glass effects with rich animations and interactions.",
    author: "tweedlex",
    category: "web",
    subcategory: "react",
    tags: ["React", "Tailwind", "动画", "组件库"],
    dateAdded: "2025-12-08",
    link: "https://github.com/tweedlex/react-magic-ui",
    demoComponent: "ReactMagicUIDemo",
    featured: true,
  },
  {
    id: "r2",
    slug: "liquid-glass-ui",
    title: "Liquid Glass UI",
    titleEn: "Liquid Glass UI",
    description: "基于 React + Tailwind + Next.js 的 Liquid Glass UI 组件库。",
    descriptionEn: "A Liquid Glass UI component library built with React, Tailwind, and Next.js.",
    author: "nibilin33",
    category: "web",
    subcategory: "react",
    tags: ["React", "Tailwind", "Next.js", "组件库"],
    dateAdded: "2025-11-21",
    link: "https://github.com/nibilin33/liquid-glass-ui",
    demoComponent: "LiquidGlassUIDemo",
    featured: true,
  },
  {
    id: "r3",
    slug: "creativoma-liquid-glass",
    title: "creativoma/liquid-glass",
    titleEn: "creativoma/liquid-glass",
    description: "React + Tailwind CSS 实现的 Liquid Glass 组件库。",
    descriptionEn: "Liquid Glass component library implemented with React and Tailwind CSS.",
    author: "Mariano Álvarez",
    category: "web",
    subcategory: "react",
    tags: ["React", "Tailwind", "开源"],
    dateAdded: "2025-12-08",
    link: "https://github.com/creativoma/liquid-glass",
    demoComponent: "CreativomaGlassDemo",
  },
  {
    id: "r4",
    slug: "liquid-glass-for-react-tailwind",
    title: "Liquid Glass for React & Tailwind",
    titleEn: "Liquid Glass for React & Tailwind",
    description: "专为 React 和 Tailwind CSS 设计的 Liquid Glass 效果组件。",
    descriptionEn: "Liquid Glass effect components designed specifically for React and Tailwind CSS.",
    author: "Eunkwang Shin",
    category: "web",
    subcategory: "react",
    tags: ["React", "Tailwind", "效果"],
    dateAdded: "2025-11-21",
    link: "https://github.com/eunkwangs/liquid-glass-react-tailwind",
    demoComponent: "ReactTailwindGlassDemo",
  },
  {
    id: "r5",
    slug: "glass-ui-react",
    title: "Glass UI React",
    titleEn: "Glass UI React",
    description: "React 平台的 Glassmorphism UI 组件库。",
    descriptionEn: "Glassmorphism UI component library for React platform.",
    author: "GlassUI Team",
    category: "web",
    subcategory: "react",
    tags: ["React", "UI组件", "Glassmorphism"],
    dateAdded: "2025-10-15",
    link: "https://github.com/glassui/react",
    demoComponent: "GlassUIDemo",
  },
  {
    id: "r6",
    slug: "frosted-glass-react",
    title: "Frosted Glass React",
    titleEn: "Frosted Glass React",
    description: "React 毛玻璃效果组件库，支持多种模糊强度。",
    descriptionEn: "React frosted glass effect library with multiple blur intensities.",
    author: "FrostDev",
    category: "web",
    subcategory: "react",
    tags: ["React", "毛玻璃", "模糊效果"],
    dateAdded: "2025-09-20",
    link: "https://github.com/frostdev/frosted-glass-react",
    demoComponent: "FrostedGlassDemo",
  },
  {
    id: "r7",
    slug: "react-glassmorphism-kit",
    title: "React Glassmorphism Kit",
    titleEn: "React Glassmorphism Kit",
    description: "React 完整 Glassmorphism 开发工具包。",
    descriptionEn: "Complete React Glassmorphism development kit.",
    author: "UIKits Inc",
    category: "web",
    subcategory: "react",
    tags: ["React", "工具包", "完整方案"],
    dateAdded: "2025-08-12",
    link: "https://github.com/uikits/react-glassmorphism-kit",
    demoComponent: "GlassmorphismKitDemo",
  },
  {
    id: "r8",
    slug: "clear-glass-react",
    title: "Clear Glass React",
    titleEn: "Clear Glass React",
    description: "React 清透玻璃效果组件。",
    descriptionEn: "React clear glass effect component.",
    author: "ClearUI",
    category: "web",
    subcategory: "react",
    tags: ["React", "清透", "玻璃效果"],
    dateAdded: "2025-07-25",
    link: "https://github.com/clearui/clear-glass-react",
    demoComponent: "ClearGlassDemo",
  },
  {
    id: "r9",
    slug: "ice-glass-react",
    title: "Ice Glass React",
    titleEn: "Ice Glass React",
    description: "React 冰晶玻璃效果组件库。",
    descriptionEn: "React ice crystal glass effect library.",
    author: "IceUI",
    category: "web",
    subcategory: "react",
    tags: ["React", "冰晶", "特效"],
    dateAdded: "2025-06-18",
    link: "https://github.com/iceui/ice-glass-react",
    demoComponent: "IceGlassDemo",
  },
  {
    id: "r10",
    slug: "crystal-react",
    title: "Crystal React",
    titleEn: "Crystal React",
    description: "React 水晶玻璃效果组件。",
    descriptionEn: "React crystal glass effect component.",
    author: "CrystalUI",
    category: "web",
    subcategory: "react",
    tags: ["React", "水晶", "透明"],
    dateAdded: "2025-05-30",
    link: "https://github.com/crystalui/crystal-react",
    demoComponent: "CrystalDemo",
  },
  {
    id: "r11",
    slug: "glassify-react",
    title: "Glassify React",
    titleEn: "Glassify React",
    description: "React 一键玻璃效果转换库。",
    descriptionEn: "React one-click glass effect conversion library.",
    author: "Glassify",
    category: "web",
    subcategory: "react",
    tags: ["React", "一键", "转换"],
    dateAdded: "2025-04-22",
    link: "https://github.com/glassify/react",
    demoComponent: "GlassifyDemo",
  },
  {
    id: "r12",
    slug: "transparent-ui-react",
    title: "Transparent UI React",
    titleEn: "Transparent UI React",
    description: "React 透明界面组件库。",
    descriptionEn: "React transparent interface component library.",
    author: "TransUI",
    category: "web",
    subcategory: "react",
    tags: ["React", "透明", "界面"],
    dateAdded: "2025-03-15",
    link: "https://github.com/transui/transparent-ui-react",
    demoComponent: "TransparentUIDemo",
  },
  {
    id: "r13",
    slug: "frost-react",
    title: "Frost React",
    titleEn: "Frost React",
    description: "React 霜冻玻璃效果组件。",
    descriptionEn: "React frosted glass effect component.",
    author: "FrostUI",
    category: "web",
    subcategory: "react",
    tags: ["React", "霜冻", "模糊"],
    dateAdded: "2025-02-28",
    link: "https://github.com/frostui/frost-react",
    demoComponent: "FrostReactDemo",
  },
  {
    id: "r14",
    slug: "glass-pane-react",
    title: "Glass Pane React",
    titleEn: "Glass Pane React",
    description: "React 玻璃面板组件，支持交互效果。",
    descriptionEn: "React glass panel component with interaction effects.",
    author: "PaneUI",
    category: "web",
    subcategory: "react",
    tags: ["React", "面板", "交互"],
    dateAdded: "2025-01-20",
    link: "https://github.com/paneui/glass-pane-react",
    demoComponent: "GlassPaneDemo",
  },
  {
    id: "r15",
    slug: "acrylic-react",
    title: "Acrylic React",
    titleEn: "Acrylic React",
    description: "React 亚克力玻璃效果组件。",
    descriptionEn: "React acrylic glass effect component.",
    author: "AcrylicUI",
    category: "web",
    subcategory: "react",
    tags: ["React", "亚克力", "磨砂"],
    dateAdded: "2024-12-15",
    link: "https://github.com/acrylicui/react",
    demoComponent: "AcrylicDemo",
  },
  {
    id: "r16",
    slug: "frosted-kit-react",
    title: "Frosted Kit React",
    titleEn: "Frosted Kit React",
    description: "React 毛玻璃效果套件。",
    descriptionEn: "React frosted glass effect kit.",
    author: "FrostKit",
    category: "web",
    subcategory: "react",
    tags: ["React", "套件", "毛玻璃"],
    dateAdded: "2024-11-08",
    link: "https://github.com/frostkit/frosted-react",
    demoComponent: "FrostedKitDemo",
  },
  {
    id: "r17",
    slug: "glass-morphism-react",
    title: "Glass Morphism React",
    titleEn: "Glass Morphism React",
    description: "React Glass Morphism 官方示例库。",
    descriptionEn: "React Glass Morphism official example library.",
    author: "GlassMorphism",
    category: "web",
    subcategory: "react",
    tags: ["React", "官方", "示例"],
    dateAdded: "2024-10-22",
    link: "https://github.com/glassmorphism/react",
    demoComponent: "GlassMorphismOfficialDemo",
  },
  {
    id: "r18",
    slug: "react-glass-effect",
    title: "React Glass Effect",
    titleEn: "React Glass Effect",
    description: "React 基础玻璃效果 Hook 和组件。",
    descriptionEn: "React basic glass effect Hooks and components.",
    author: "EffectUI",
    category: "web",
    subcategory: "react",
    tags: ["React", "Hooks", "基础"],
    dateAdded: "2024-09-15",
    link: "https://github.com/effectui/react-glass-effect",
    demoComponent: "ReactGlassEffectDemo",
  },
  {
    id: "r19",
    slug: "zen-glass-react",
    title: "Zen Glass React",
    titleEn: "Zen Glass React",
    description: "React 禅意玻璃效果组件。",
    descriptionEn: "React zen glass effect component.",
    author: "ZenUI",
    category: "web",
    subcategory: "react",
    tags: ["React", "禅意", "简约"],
    dateAdded: "2024-08-28",
    link: "https://github.com/zenui/glass-react",
    demoComponent: "ZenGlassDemo",
  },
  {
    id: "r20",
    slug: "nebula-glass-react",
    title: "Nebula Glass React",
    titleEn: "Nebula Glass React",
    description: "React 星云玻璃效果组件。",
    descriptionEn: "React nebula glass effect component.",
    author: "NebulaUI",
    category: "web",
    subcategory: "react",
    tags: ["React", "星云", "渐变"],
    dateAdded: "2024-07-12",
    link: "https://github.com/nebula-ui/glass-react",
    demoComponent: "NebulaGlassDemo",
  },

  // ==================== VUE (8个) ====================
  {
    id: "v1",
    slug: "vue-liquid-glass",
    title: "vue-liquid-glass",
    titleEn: "vue-liquid-glass",
    description: "Vue 3 平台的 Liquid Glass 组件库，提供声明式的玻璃效果。",
    descriptionEn: "A Vue 3 component library for Liquid Glass effects with declarative API.",
    author: "Daiigu",
    category: "web",
    subcategory: "vue",
    tags: ["Vue 3", "组件库", "TypeScript"],
    dateAdded: "2025-12-08",
    link: "https://github.com/daiigu/vue-liquid-glass",
    demoComponent: "VueLiquidDemo",
    featured: true,
  },
  {
    id: "v2",
    slug: "vue-glassmorphism",
    title: "Vue Glassmorphism",
    titleEn: "Vue Glassmorphism",
    description: "Vue 3 Glassmorphism 组件库。",
    descriptionEn: "Vue 3 Glassmorphism component library.",
    author: "VueGlass",
    category: "web",
    subcategory: "vue",
    tags: ["Vue 3", "Glassmorphism"],
    dateAdded: "2025-10-05",
    link: "https://github.com/vueglass/vue-morphism",
    demoComponent: "VueGlassMorphismDemo",
  },
  {
    id: "v3",
    slug: "vue-frosted-glass",
    title: "Vue Frosted Glass",
    titleEn: "Vue Frosted Glass",
    description: "Vue 毛玻璃效果组件。",
    descriptionEn: "Vue frosted glass effect component.",
    author: "FrostVue",
    category: "web",
    subcategory: "vue",
    tags: ["Vue", "毛玻璃", "效果"],
    dateAdded: "2025-08-20",
    link: "https://github.com/frostvue/frosted-glass",
    demoComponent: "VueFrostedDemo",
  },
  {
    id: "v4",
    slug: "vue-glass-ui",
    title: "Vue Glass UI",
    titleEn: "Vue Glass UI",
    description: "Vue 3 玻璃界面组件库。",
    descriptionEn: "Vue 3 glass interface component library.",
    author: "GlassVue",
    category: "web",
    subcategory: "vue",
    tags: ["Vue 3", "UI组件"],
    dateAdded: "2025-06-15",
    link: "https://github.com/glassvue/ui",
    demoComponent: "VueGlassUIDemo",
  },
  {
    id: "v5",
    slug: "vue-acrylic",
    title: "Vue Acrylic",
    titleEn: "Vue Acrylic",
    description: "Vue 亚克力效果组件。",
    descriptionEn: "Vue acrylic effect component.",
    author: "AcrylicVue",
    category: "web",
    subcategory: "vue",
    tags: ["Vue", "亚克力"],
    dateAdded: "2025-04-10",
    link: "https://github.com/acrylicvue/vue-acrylic",
    demoComponent: "VueAcrylicDemo",
  },
  {
    id: "v6",
    slug: "vue-clear-glass",
    title: "Vue Clear Glass",
    titleEn: "Vue Clear Glass",
    description: "Vue 清透玻璃效果。",
    descriptionEn: "Vue clear glass effect.",
    author: "ClearVue",
    category: "web",
    subcategory: "vue",
    tags: ["Vue", "清透"],
    dateAdded: "2025-02-25",
    link: "https://github.com/clearvue/clear-glass",
    demoComponent: "VueClearGlassDemo",
  },
  {
    id: "v7",
    slug: "vue-glass-card",
    title: "Vue Glass Card",
    titleEn: "Vue Glass Card",
    description: "Vue 玻璃卡片组件。",
    descriptionEn: "Vue glass card component.",
    author: "CardVue",
    category: "web",
    subcategory: "vue",
    tags: ["Vue", "卡片"],
    dateAdded: "2024-12-20",
    link: "https://github.com/cardvue/glass-card",
    demoComponent: "VueGlassCardDemo",
  },
  {
    id: "v8",
    slug: "nuxt-glass",
    title: "Nuxt Glass",
    titleEn: "Nuxt Glass",
    description: "Nuxt 3 玻璃效果模块。",
    descriptionEn: "Nuxt 3 glass effect module.",
    author: "NuxtUI",
    category: "web",
    subcategory: "vue",
    tags: ["Nuxt 3", "模块"],
    dateAdded: "2024-10-15",
    link: "https://github.com/nuxtui/glass",
    demoComponent: "NuxtGlassDemo",
  },

  // ==================== TAILWIND CSS (10个) ====================
  {
    id: "t1",
    slug: "tailwind-css-liquid-glass",
    title: "Tailwind CSS Liquid Glass",
    titleEn: "Tailwind CSS Liquid Glass",
    description: "Tailwind CSS 插件，提供便捷的 Liquid Glass 工具类。",
    descriptionEn: "Tailwind CSS plugin providing convenient Liquid Glass utility classes.",
    author: "Italo Almeida",
    category: "web",
    subcategory: "tailwind",
    tags: ["Tailwind", "插件", "工具类"],
    dateAdded: "2025-11-21",
    link: "https://github.com/italoalmeida/tailwind-css-liquid-glass",
    demoComponent: "TailwindPluginDemo",
    featured: true,
  },
  {
    id: "t2",
    slug: "water",
    title: "Water",
    titleEn: "Water",
    description: "基于 Tailwind 的 Liquid Glass 效果演示和组件库。",
    descriptionEn: "Liquid Glass effect demo and component library based on Tailwind.",
    author: "Henry Oman",
    category: "web",
    subcategory: "tailwind",
    tags: ["Tailwind", "演示", "组件库"],
    dateAdded: "2025-11-21",
    link: "https://github.com/henryoman/water",
    demoComponent: "WaterDemo",
  },
  {
    id: "t3",
    slug: "glawindui",
    title: "glawindui — Liquid Glass UI",
    titleEn: "glawindui — Liquid Glass UI",
    description: "基于 Tailwind CSS 的 Liquid Glass UI 组件库。",
    descriptionEn: "Liquid Glass UI component library based on Tailwind CSS.",
    author: "Ali Samei",
    category: "web",
    subcategory: "tailwind",
    tags: ["Tailwind", "组件库", "UI"],
    dateAdded: "2025-11-21",
    link: "https://github.com/alisamei/glawindui",
    demoComponent: "GlawinduiDemo",
  },
  {
    id: "t4",
    slug: "tailwind-glassmorphism",
    title: "Tailwind Glassmorphism",
    titleEn: "Tailwind Glassmorphism",
    description: "Tailwind CSS Glassmorphism 插件。",
    descriptionEn: "Tailwind CSS Glassmorphism plugin.",
    author: "TailwindGlass",
    category: "web",
    subcategory: "tailwind",
    tags: ["Tailwind", "Glassmorphism", "插件"],
    dateAdded: "2025-09-08",
    link: "https://github.com/tailwindglass/glassmorphism",
    demoComponent: "TailwindGlassmorphismDemo",
  },
  {
    id: "t5",
    slug: "tailwind-frosted-glass",
    title: "Tailwind Frosted Glass",
    titleEn: "Tailwind Frosted Glass",
    description: "Tailwind CSS 毛玻璃效果插件。",
    descriptionEn: "Tailwind CSS frosted glass effect plugin.",
    author: "FrostTailwind",
    category: "web",
    subcategory: "tailwind",
    tags: ["Tailwind", "毛玻璃", "插件"],
    dateAdded: "2025-07-22",
    link: "https://github.com/frosttailwind/frosted-glass",
    demoComponent: "TailwindFrostedDemo",
  },
  {
    id: "t6",
    slug: "tailwind-blur",
    title: "Tailwind Blur",
    titleEn: "Tailwind Blur",
    description: "Tailwind CSS 模糊效果扩展。",
    descriptionEn: "Tailwind CSS blur effect extension.",
    author: "BlurTailwind",
    category: "web",
    subcategory: "tailwind",
    tags: ["Tailwind", "模糊", "扩展"],
    dateAdded: "2025-05-18",
    link: "https://github.com/blurtailwind/blur",
    demoComponent: "TailwindBlurDemo",
  },
  {
    id: "t7",
    slug: "tailwind-backdrop",
    title: "Tailwind Backdrop",
    titleEn: "Tailwind Backdrop",
    description: "Tailwind CSS backdrop 效果插件。",
    descriptionEn: "Tailwind CSS backdrop effect plugin.",
    author: "BackdropUI",
    category: "web",
    subcategory: "tailwind",
    tags: ["Tailwind", "backdrop", "背景"],
    dateAdded: "2025-03-25",
    link: "https://github.com/backdroptailwind/backdrop",
    demoComponent: "TailwindBackdropDemo",
  },
  {
    id: "t8",
    slug: "tailwind-acrylic",
    title: "Tailwind Acrylic",
    titleEn: "Tailwind Acrylic",
    description: "Tailwind CSS 亚克力效果插件。",
    descriptionEn: "Tailwind CSS acrylic effect plugin.",
    author: "AcrylicTailwind",
    category: "web",
    subcategory: "tailwind",
    tags: ["Tailwind", "亚克力"],
    dateAdded: "2025-01-15",
    link: "https://github.com/acrylictailwind/acrylic",
    demoComponent: "TailwindAcrylicDemo",
  },
  {
    id: "t9",
    slug: "tailwind-glass",
    title: "Tailwind Glass",
    titleEn: "Tailwind Glass",
    description: "Tailwind CSS 基础玻璃效果插件。",
    descriptionEn: "Tailwind CSS basic glass effect plugin.",
    author: "GlassTailwind",
    category: "web",
    subcategory: "tailwind",
    tags: ["Tailwind", "基础", "插件"],
    dateAdded: "2024-11-20",
    link: "https://github.com/glasstailwind/glass",
    demoComponent: "TailwindGlassDemo",
  },
  {
    id: "t10",
    slug: "tailwind-frost",
    title: "Tailwind Frost",
    titleEn: "Tailwind Frost",
    description: "Tailwind CSS 霜冻效果插件。",
    descriptionEn: "Tailwind CSS frost effect plugin.",
    author: "FrostTail",
    category: "web",
    subcategory: "tailwind",
    tags: ["Tailwind", "霜冻"],
    dateAdded: "2024-09-05",
    link: "https://github.com/frosttail/frost",
    demoComponent: "TailwindFrostDemo",
  },

  // ==================== PURE CSS (8个) ====================
  {
    id: "c1",
    slug: "feature-liquidglass",
    title: "feature-liquidglass",
    titleEn: "feature-liquidglass",
    description: "纯 HTML/CSS 实现的 Liquid Glass 基础效果，适合学习原理。",
    descriptionEn: "Pure HTML/CSS implementation of basic Liquid Glass effects, perfect for learning the fundamentals.",
    author: "Ander Marlon",
    category: "web",
    subcategory: "css",
    tags: ["HTML", "CSS", "基础"],
    dateAdded: "2025-12-08",
    link: "https://github.com/andermarlon/feature-liquidglass",
    demoComponent: "FeatureLiquidDemo",
  },
  {
    id: "c2",
    slug: "apple-liquid-glass-ui-2025",
    title: "Apple Liquid Glass UI (2025)",
    titleEn: "Apple Liquid Glass UI (2025)",
    description: "2025 年最新风格的 Apple 风格 Liquid Glass UI 效果。",
    descriptionEn: "Latest 2025 Apple-style Liquid Glass UI effects.",
    author: "Avaz Bokiev",
    category: "web",
    subcategory: "css",
    tags: ["CSS", "Apple", "设计"],
    dateAdded: "2025-11-21",
    link: "https://github.com/avazbokiev/apple-liquid-glass-ui-2025",
    demoComponent: "AppleGlassUIDemo",
    featured: true,
  },
  {
    id: "c3",
    slug: "apple-liquid-glass-witcher",
    title: "Apple Liquid Glass Switcher",
    titleEn: "Apple Liquid Glass Switcher",
    description: "CSS + JavaScript 实现的交互式 Liquid Glass 切换效果。",
    descriptionEn: "Interactive Liquid Glass switcher implemented with CSS + JavaScript.",
    author: "Den Dionigi",
    category: "web",
    subcategory: "css",
    tags: ["CSS", "JavaScript", "交互"],
    dateAdded: "2025-11-21",
    link: "https://github.com/dendionigi/apple-liquid-glass-witcher",
    demoComponent: "AppleSwitcherDemo",
  },
  {
    id: "c4",
    slug: "pure-css-apple-liquid-glass-user-card",
    title: "Pure CSS Apple Liquid Glass User Card",
    titleEn: "Pure CSS Apple Liquid Glass User Card",
    description: "纯 CSS 实现的 Apple 风格用户卡片 Liquid Glass 效果。",
    descriptionEn: "Pure CSS implementation of Apple-style user card with Liquid Glass effects.",
    author: "Kumar Anirudha",
    category: "web",
    subcategory: "css",
    tags: ["CSS", "用户卡片", "设计"],
    dateAdded: "2025-11-21",
    link: "https://github.com/kumaranirudha/pure-css-liquid-glass-user-card",
    demoComponent: "UserCardDemo",
  },
  {
    id: "c5",
    slug: "css-glassmorphism",
    title: "CSS Glassmorphism",
    titleEn: "CSS Glassmorphism",
    description: "纯 CSS Glassmorphism 效果集合。",
    descriptionEn: "Pure CSS Glassmorphism effect collection.",
    author: "CSSGallery",
    category: "web",
    subcategory: "css",
    tags: ["CSS", "集合", "效果"],
    dateAdded: "2025-08-15",
    link: "https://github.com/cssgallery/glassmorphism",
    demoComponent: "CSSGlassmorphismDemo",
  },
  {
    id: "c6",
    slug: "css-backdrop-filter",
    title: "CSS Backdrop Filter",
    titleEn: "CSS Backdrop Filter",
    description: "CSS backdrop-filter 属性详解和示例。",
    descriptionEn: "CSS backdrop-filter property detailed explanation and examples.",
    author: "CSSFilters",
    category: "web",
    subcategory: "css",
    tags: ["CSS", "backdrop-filter", "教程"],
    dateAdded: "2025-06-10",
    link: "https://github.com/cssfilters/backdrop-filter",
    demoComponent: "CSSBackdropDemo",
  },
  {
    id: "c7",
    slug: "glass-card-css",
    title: "Glass Card CSS",
    titleEn: "Glass Card CSS",
    description: "纯 CSS 玻璃卡片效果。",
    descriptionEn: "Pure CSS glass card effect.",
    author: "CardCSS",
    category: "web",
    subcategory: "css",
    tags: ["CSS", "卡片"],
    dateAdded: "2025-03-28",
    link: "https://github.com/cardcss/glass-card",
    demoComponent: "GlassCardCSSDemo",
  },
  {
    id: "c8",
    slug: "animated-glass-css",
    title: "Animated Glass CSS",
    titleEn: "Animated Glass CSS",
    description: "带动画的 CSS 玻璃效果。",
    descriptionEn: "Animated CSS glass effect.",
    author: "AnimatedCSS",
    category: "web",
    subcategory: "css",
    tags: ["CSS", "动画"],
    dateAdded: "2024-12-10",
    link: "https://github.com/animatedcss/glass",
    demoComponent: "AnimatedGlassCSSDemo",
  },

  // ==================== FLUTTER (6个) ====================
  {
    id: "f1",
    slug: "liquidglass-navbar",
    title: "LiquidGlass NavBar",
    titleEn: "LiquidGlass NavBar",
    description: "Flutter 平台的 Liquid Glass 导航栏组件。",
    descriptionEn: "Liquid Glass navigation bar component for Flutter platform.",
    author: "Zyad Wael",
    category: "mobile",
    subcategory: "flutter",
    tags: ["Flutter", "导航栏", "组件"],
    dateAdded: "2025-12-08",
    link: "https://github.com/zyadwael/liquidglass-navbar",
    demoComponent: "FlutterNavbarDemo",
  },
  {
    id: "f2",
    slug: "oneclient",
    title: "OneClient",
    titleEn: "OneClient",
    description: "Flutter 完整应用，展示 Liquid Glass 在实际应用中的使用。",
    descriptionEn: "Complete Flutter app demonstrating Liquid Glass usage in production.",
    author: "Heyarny",
    category: "mobile",
    subcategory: "flutter",
    tags: ["Flutter", "完整应用", "示例"],
    dateAdded: "2025-11-06",
    link: "https://github.com/heyarny/oneclient",
    demoComponent: "OneClientDemo",
  },
  {
    id: "f3",
    slug: "flutter-glassmorphism",
    title: "Flutter Glassmorphism",
    titleEn: "Flutter Glassmorphism",
    description: "Flutter Glassmorphism 组件库。",
    descriptionEn: "Flutter Glassmorphism component library.",
    author: "FlutterGlass",
    category: "mobile",
    subcategory: "flutter",
    tags: ["Flutter", "Glassmorphism"],
    dateAdded: "2025-08-25",
    link: "https://github.com/flutterglass/morphism",
    demoComponent: "FlutterGlassmorphismDemo",
  },
  {
    id: "f4",
    slug: "flutter-frosted-glass",
    title: "Flutter Frosted Glass",
    titleEn: "Flutter Frosted Glass",
    description: "Flutter 毛玻璃效果组件。",
    descriptionEn: "Flutter frosted glass effect component.",
    author: "FrostFlutter",
    category: "mobile",
    subcategory: "flutter",
    tags: ["Flutter", "毛玻璃"],
    dateAdded: "2025-06-15",
    link: "https://github.com/frostflutter/frosted-glass",
    demoComponent: "FlutterFrostedDemo",
  },
  {
    id: "f5",
    slug: "flutter-acrylic",
    title: "Flutter Acrylic",
    titleEn: "Flutter Acrylic",
    description: "Flutter 亚克力效果组件。",
    descriptionEn: "Flutter acrylic effect component.",
    author: "AcrylicFlutter",
    category: "mobile",
    subcategory: "flutter",
    tags: ["Flutter", "亚克力"],
    dateAdded: "2025-03-20",
    link: "https://github.com/acrylicflutter/acrylic",
    demoComponent: "FlutterAcrylicDemo",
  },
  {
    id: "f6",
    slug: "glass-container-flutter",
    title: "Glass Container Flutter",
    titleEn: "Glass Container Flutter",
    description: "Flutter 玻璃容器组件。",
    descriptionEn: "Flutter glass container component.",
    author: "ContainerFlutter",
    category: "mobile",
    subcategory: "flutter",
    tags: ["Flutter", "容器"],
    dateAdded: "2024-11-15",
    link: "https://github.com/containerflutter/glass",
    demoComponent: "FlutterContainerDemo",
  },

  // ==================== ANDROID (4个) ====================
  {
    id: "a1",
    slug: "apple-liquid-glass-android",
    title: "Apple Liquid Glass for Android",
    titleEn: "Apple Liquid Glass for Android",
    description: "在 Android 平台上实现 Apple 风格的 Liquid Glass 效果。",
    descriptionEn: "Apple-style Liquid Glass effects implementation for Android platform.",
    author: "Sid Zadaun",
    category: "mobile",
    subcategory: "android",
    tags: ["Android", "Kotlin", "UI"],
    dateAdded: "2025-12-08",
    link: "https://github.com/sidzadaun/apple-liquid-glass-android",
    demoComponent: "AndroidAppleGlassDemo",
    featured: true,
  },
  {
    id: "a2",
    slug: "android-glassmorphism",
    title: "Android Glassmorphism",
    titleEn: "Android Glassmorphism",
    description: "Android Glassmorphism 组件库。",
    descriptionEn: "Android Glassmorphism component library.",
    author: "AndroidGlass",
    category: "mobile",
    subcategory: "android",
    tags: ["Android", "Glassmorphism", "Kotlin"],
    dateAdded: "2025-07-30",
    link: "https://github.com/androidglass/glassmorphism",
    demoComponent: "AndroidGlassmorphismDemo",
  },
  {
    id: "a3",
    slug: "android-frosted-glass",
    title: "Android Frosted Glass",
    titleEn: "Android Frosted Glass",
    description: "Android 毛玻璃效果库。",
    descriptionEn: "Android frosted glass effect library.",
    author: "FrostAndroid",
    category: "mobile",
    subcategory: "android",
    tags: ["Android", "毛玻璃"],
    dateAdded: "2025-04-25",
    link: "https://github.com/frostandroid/frosted-glass",
    demoComponent: "AndroidFrostedDemo",
  },
  {
    id: "a4",
    slug: "android-blur-view",
    title: "Android Blur View",
    titleEn: "Android Blur View",
    description: "Android 模糊视图组件。",
    descriptionEn: "Android blur view component.",
    author: "BlurAndroid",
    category: "mobile",
    subcategory: "android",
    tags: ["Android", "模糊", "View"],
    dateAdded: "2024-12-05",
    link: "https://github.com/blurandroid/blur-view",
    demoComponent: "AndroidBlurDemo",
  },

  // ==================== IOS/SWIFT (4个) ====================
  {
    id: "i1",
    slug: "dskit",
    title: "DSKit",
    titleEn: "DSKit",
    description: "Swift 实现的 iOS 风格 Liquid Glass 组件库。",
    descriptionEn: "iOS-style Liquid Glass component library implemented in Swift.",
    author: "Norman Sanchez",
    category: "mobile",
    subcategory: "ios",
    tags: ["iOS", "Swift", "组件库"],
    dateAdded: "2025-11-21",
    link: "https://github.com/normansanchez/dskit",
    demoComponent: "DSKitDemo",
  },
  {
    id: "i2",
    slug: "ios-glassmorphism",
    title: "iOS Glassmorphism",
    titleEn: "iOS Glassmorphism",
    description: "iOS Glassmorphism SwiftUI 组件库。",
    descriptionEn: "iOS Glassmorphism SwiftUI component library.",
    author: "iOSGlass",
    category: "mobile",
    subcategory: "ios",
    tags: ["iOS", "SwiftUI", "Glassmorphism"],
    dateAdded: "2025-06-20",
    link: "https://github.com/iosglass/glassmorphism",
    demoComponent: "iOSGlassmorphismDemo",
  },
  {
    id: "i3",
    slug: "swiftui-glass",
    title: "SwiftUI Glass",
    titleEn: "SwiftUI Glass",
    description: "SwiftUI 玻璃效果组件。",
    descriptionEn: "SwiftUI glass effect component.",
    author: "SwiftUIGlass",
    category: "mobile",
    subcategory: "ios",
    tags: ["SwiftUI", "组件"],
    dateAdded: "2025-03-15",
    link: "https://github.com/swiftuiglass/glass",
    demoComponent: "SwiftUIGlassDemo",
  },
  {
    id: "i4",
    slug: "ios-blur",
    title: "iOS Blur",
    titleEn: "iOS Blur",
    description: "iOS 模糊效果 Swift 库。",
    descriptionEn: "iOS blur effect Swift library.",
    author: "BluriOS",
    category: "mobile",
    subcategory: "ios",
    tags: ["iOS", "模糊", "Swift"],
    dateAdded: "2024-10-20",
    link: "https://github.com/blurios/blur",
    demoComponent: "iOSBlurDemo",
  },

  // ==================== REACT NATIVE (3个) ====================
  {
    id: "rn1",
    slug: "react-native-glass-effect-view",
    title: "react-native-glass-effect-view",
    titleEn: "react-native-glass-effect-view",
    description: "React Native 平台的玻璃效果组件。",
    descriptionEn: "Glass effect component for React Native platform.",
    author: "Thomas Schoffelen",
    category: "mobile",
    subcategory: "react-native",
    tags: ["React Native", "组件", "效果"],
    dateAdded: "2025-11-06",
    link: "https://github.com/thomasschoffelen/react-native-glass-effect-view",
    demoComponent: "ReactNativeGlassDemo",
    featured: true,
  },
  {
    id: "rn2",
    slug: "rn-glassmorphism",
    title: "RN Glassmorphism",
    titleEn: "RN Glassmorphism",
    description: "React Native Glassmorphism 组件库。",
    descriptionEn: "React Native Glassmorphism component library.",
    author: "RNGlass",
    category: "mobile",
    subcategory: "react-native",
    tags: ["React Native", "Glassmorphism"],
    dateAdded: "2025-07-10",
    link: "https://github.com/rnglass/morphism",
    demoComponent: "RNGlassmorphismDemo",
  },
  {
    id: "rn3",
    slug: "react-native-blur",
    title: "React Native Blur",
    titleEn: "React Native Blur",
    description: "React Native 模糊效果组件。",
    descriptionEn: "React Native blur effect component.",
    author: "BlurRN",
    category: "mobile",
    subcategory: "react-native",
    tags: ["React Native", "模糊"],
    dateAdded: "2025-02-28",
    link: "https://github.com/blurrn/blur",
    demoComponent: "RNBlurDemo",
  },

  // ==================== JETPACK COMPOSE (3个) ====================
  {
    id: "jc1",
    slug: "android-liquid-glass-view",
    title: "AndroidLiquidGlass View",
    titleEn: "AndroidLiquidGlass View",
    description: "Jetpack Compose 实现的 Android Liquid Glass 组件。",
    descriptionEn: "Android Liquid Glass component implemented with Jetpack Compose.",
    author: "QmDeve",
    category: "mobile",
    subcategory: "jetpack-compose",
    tags: ["Android", "Jetpack Compose", "Kotlin"],
    dateAdded: "2025-11-06",
    link: "https://github.com/qmdeve/android-liquid-glass-view",
    demoComponent: "ComposeGlassDemo",
  },
  {
    id: "jc2",
    slug: "compose-glassmorphism",
    title: "Compose Glassmorphism",
    titleEn: "Compose Glassmorphism",
    description: "Jetpack Compose Glassmorphism 组件。",
    descriptionEn: "Jetpack Compose Glassmorphism component.",
    author: "ComposeGlass",
    category: "mobile",
    subcategory: "jetpack-compose",
    tags: ["Compose", "Glassmorphism"],
    dateAdded: "2025-05-20",
    link: "https://github.com/composeglass/glassmorphism",
    demoComponent: "ComposeGlassmorphismDemo",
  },
  {
    id: "jc3",
    slug: "compose-blur",
    title: "Compose Blur",
    titleEn: "Compose Blur",
    description: "Jetpack Compose 模糊效果组件。",
    descriptionEn: "Jetpack Compose blur effect component.",
    author: "BlurCompose",
    category: "mobile",
    subcategory: "jetpack-compose",
    tags: ["Compose", "模糊"],
    dateAdded: "2024-11-10",
    link: "https://github.com/blurcompose/blur",
    demoComponent: "ComposeBlurDemo",
  },

  // ==================== FIGMA (4个) ====================
  {
    id: "fg1",
    slug: "ios-glass-figma",
    title: "iOS Glass",
    titleEn: "iOS Glass",
    description: "Figma 设计的 iOS 风格玻璃效果资源包。",
    descriptionEn: "Figma design resource package for iOS-style glass effects.",
    author: "Timothy Rick",
    category: "design",
    subcategory: "figma",
    tags: ["Figma", "设计资源", "iOS"],
    dateAdded: "2025-11-06",
    link: "https://figma.com/community/file/123456789/ios-glass",
    demoComponent: "FigmaGlassDemo",
    featured: true,
  },
  {
    id: "fg2",
    slug: "glassmorphism-kit-figma",
    title: "Glassmorphism Kit",
    titleEn: "Glassmorphism Kit",
    description: "完整的 Glassmorphism 设计工具包。",
    descriptionEn: "Complete Glassmorphism design toolkit.",
    author: "DesignCo",
    category: "design",
    subcategory: "figma",
    tags: ["Figma", "工具包", "设计"],
    dateAdded: "2025-09-15",
    link: "https://figma.com/community/file/123456789/glassmorphism-kit",
    demoComponent: "GlassmorphismKitDemo",
  },
  {
    id: "fg3",
    slug: "glass-cards-figma",
    title: "Glass Cards Figma",
    titleEn: "Glass Cards Figma",
    description: "Figma 玻璃卡片设计模板。",
    descriptionEn: "Figma glass card design templates.",
    author: "CardDesign",
    category: "design",
    subcategory: "figma",
    tags: ["Figma", "卡片", "模板"],
    dateAdded: "2025-05-22",
    link: "https://figma.com/community/file/123456789/glass-cards",
    demoComponent: "FigmaCardsDemo",
  },
  {
    id: "fg4",
    slug: "glass-ui-kit-figma",
    title: "Glass UI Kit",
    titleEn: "Glass UI Kit",
    description: "Figma 玻璃界面设计套件。",
    descriptionEn: "Figma glass interface design kit.",
    author: "UIKitFigma",
    category: "design",
    subcategory: "figma",
    tags: ["Figma", "UI套件"],
    dateAdded: "2024-12-18",
    link: "https://figma.com/community/file/123456789/glass-ui-kit",
    demoComponent: "FigmaUIKitDemo",
  },

  // ==================== FRAMER (4个) ====================
  {
    id: "fr1",
    slug: "liquid-glass-animation-framer",
    title: "Liquid Glass Animation",
    titleEn: "Liquid Glass Animation",
    description: "Framer 设计的 Liquid Glass 动画资源包。",
    descriptionEn: "Framer design resource package for Liquid Glass animations.",
    author: "Become™ | Possibilities Answered",
    category: "design",
    subcategory: "framer",
    tags: ["Framer", "动画", "设计资源"],
    dateAdded: "2025-11-06",
    link: "https://framer.com/community/liquid-glass-animation",
    demoComponent: "FramerAnimationDemo",
  },
  {
    id: "fr2",
    slug: "glassmorphism-framer",
    title: "Glassmorphism Framer",
    titleEn: "Glassmorphism Framer",
    description: "Framer Glassmorphism 组件模板。",
    descriptionEn: "Framer Glassmorphism component templates.",
    author: "FramerGlass",
    category: "design",
    subcategory: "framer",
    tags: ["Framer", "组件", "模板"],
    dateAdded: "2025-07-08",
    link: "https://framer.com/community/glassmorphism",
    demoComponent: "FramerGlassmorphismDemo",
  },
  {
    id: "fr3",
    slug: "glass-cards-framer",
    title: "Glass Cards Framer",
    titleEn: "Glass Cards Framer",
    description: "Framer 玻璃卡片动画模板。",
    descriptionEn: "Framer glass card animation templates.",
    author: "FramerCards",
    category: "design",
    subcategory: "framer",
    tags: ["Framer", "卡片", "动画"],
    dateAdded: "2025-03-25",
    link: "https://framer.com/community/glass-cards",
    demoComponent: "FramerCardsDemo",
  },
  {
    id: "fr4",
    slug: "interactive-glass-framer",
    title: "Interactive Glass Framer",
    titleEn: "Interactive Glass Framer",
    description: "Framer 交互式玻璃效果模板。",
    descriptionEn: "Framer interactive glass effect templates.",
    author: "InteractiveFramer",
    category: "design",
    subcategory: "framer",
    tags: ["Framer", "交互"],
    dateAdded: "2024-10-12",
    link: "https://framer.com/community/interactive-glass",
    demoComponent: "InteractiveGlassFramerDemo",
  },

  // ==================== WEBFLOW (3个) ====================
  {
    id: "wf1",
    slug: "ios-glass-webflow",
    title: "iOS Glass (Design)",
    titleEn: "iOS Glass (Design)",
    description: "Webflow 模板 - iOS 风格玻璃效果设计。",
    descriptionEn: "Webflow template with iOS-style glass effect design.",
    author: "Timothy Rick",
    category: "design",
    subcategory: "webflow",
    tags: ["Webflow", "模板", "设计"],
    dateAdded: "2025-11-06",
    link: "https://webflow.com/templates/ios-glass",
    demoComponent: "WebflowGlassDemo",
  },
  {
    id: "wf2",
    slug: "glassmorphism-webflow",
    title: "Glassmorphism Webflow",
    titleEn: "Glassmorphism Webflow",
    description: "Webflow Glassmorphism 模板。",
    descriptionEn: "Webflow Glassmorphism template.",
    author: "WebflowGlass",
    category: "design",
    subcategory: "webflow",
    tags: ["Webflow", "模板", "Glassmorphism"],
    dateAdded: "2025-06-15",
    link: "https://webflow.com/templates/glassmorphism",
    demoComponent: "WebflowGlassmorphismDemo",
  },
  {
    id: "wf3",
    slug: "glass-cards-webflow",
    title: "Glass Cards Webflow",
    titleEn: "Glass Cards Webflow",
    description: "Webflow 玻璃卡片模板集合。",
    descriptionEn: "Webflow glass card template collection.",
    author: "WebflowCards",
    category: "design",
    subcategory: "webflow",
    tags: ["Webflow", "卡片", "模板"],
    dateAdded: "2025-02-20",
    link: "https://webflow.com/templates/glass-cards",
    demoComponent: "WebflowCardsDemo",
  },
];

// Helper functions
export function getResourcesByCategory(category: Category): Resource[] {
  return resources.filter(r => r.category === category);
}

export function getResourcesBySubcategory(subcategory: Subcategory): Resource[] {
  return resources.filter(r => r.subcategory === subcategory);
}

export function getResourceBySlug(slug: string): Resource | undefined {
  return resources.find(r => r.slug === slug);
}

export function getFeaturedResources(): Resource[] {
  return resources.filter(r => r.featured);
}

export function getAllCategories(): { category: Category; count: number; subcategories: Subcategory[] }[] {
  const categories: Category[] = ["mobile", "web", "design"];
  return categories.map(cat => ({
    category: cat,
    count: resources.filter(r => r.category === cat).length,
    subcategories: [...new Set(resources.filter(r => r.category === cat).map(r => r.subcategory))],
  }));
}

export function getSubcategoryName(subcategory: Subcategory, locale: "zh-CN" | "en"): string {
  const names: Record<Subcategory, { zh: string; en: string }> = {
    android: { zh: "Android", en: "Android" },
    ios: { zh: "iOS", en: "iOS" },
    "react-native": { zh: "React Native", en: "React Native" },
    flutter: { zh: "Flutter", en: "Flutter" },
    "jetpack-compose": { zh: "Jetpack Compose", en: "Jetpack Compose" },
    react: { zh: "React", en: "React" },
    vue: { zh: "Vue", en: "Vue" },
    svelte: { zh: "Svelte", en: "Svelte" },
    css: { zh: "CSS", en: "CSS" },
    tailwind: { zh: "Tailwind CSS", en: "Tailwind CSS" },
    figma: { zh: "Figma", en: "Figma" },
    framer: { zh: "Framer", en: "Framer" },
    webflow: { zh: "Webflow", en: "Webflow" },
  };
  return locale === "zh-CN" ? names[subcategory].zh : names[subcategory].en;
}

export function getCategoryName(category: Category, locale: "zh-CN" | "en"): string {
  const names: Record<Category, { zh: string; en: string }> = {
    mobile: { zh: "移动开发", en: "Mobile Development" },
    web: { zh: "Web 开发", en: "Web Development" },
    design: { zh: "设计资源", en: "Design Resources" },
  };
  return locale === "zh-CN" ? names[category].zh : names[category].en;
}
